### ISSUE TITLE
Show "Pick up T Shirt later" on the ticket

### ISSUE THREAD

**Issue by jaspervdj** [zfoh/zureg#35]
For attendees who registered after May 7, 5PM GMT+2, we show the following note during registration:

> Please note that we have ordered the T-Shirts and cannot guarantee that you will receive one if you register at this time.

We should show a "pick up T-Shirt later" note on their ticket, so it also appears when scanning.  They won't receive a T-Shirt during the registration, but will have an option to pick one up the last day since there should be some leftovers.

**Comment by littc** [comment]
#36
